# Generated by Django 3.2.5 on 2021-07-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('work', models.CharField(max_length=50, null=True)),
                ('f_link', models.CharField(max_length=50, null=True)),
                ('t_link', models.CharField(max_length=50, null=True)),
                ('I_link', models.CharField(max_length=50, null=True)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
