# Generated by Django 3.2.5 on 2021-07-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mweb', '0002_ourteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='profile',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
