# Generated by Django 3.2.5 on 2021-07-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mweb', '0004_ourteam2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam2',
            name='text2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
