# Generated by Django 3.2.5 on 2021-07-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mweb', '0005_alter_ourteam2_text2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
