# Generated by Django 3.2.5 on 2021-07-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mweb', '0006_alter_ourteam_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ilink', models.CharField(max_length=200)),
                ('s_discription', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('p1', models.TextField(blank=True, null=True)),
                ('p2', models.TextField(blank=True, null=True)),
                ('p3', models.TextField(blank=True, null=True)),
                ('p4', models.TextField(blank=True, null=True)),
                ('p5', models.TextField(blank=True, null=True)),
                ('p6', models.TextField(blank=True, null=True)),
                ('title2', models.CharField(blank=True, max_length=50, null=True)),
                ('ilink2', models.CharField(blank=True, max_length=200, null=True)),
                ('s_discription2', models.TextField(blank=True, null=True)),
                ('content2', models.TextField(blank=True, null=True)),
                ('video_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
