# Generated by Django 3.2.5 on 2021-07-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mweb', '0008_alter_blog_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='video_link',
        ),
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='clips'),
        ),
    ]
