# Generated by Django 3.2.5 on 2021-07-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mweb', '0009_auto_20210730_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_link', models.CharField(blank=True, max_length=300, null=True)),
                ('post', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
