# Generated by Django 3.2.5 on 2021-07-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mweb', '0012_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cdate',
            field=models.CharField(max_length=20),
        ),
    ]
