# Generated by Django 3.2.5 on 2021-07-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mweb', '0013_alter_certificate_cdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='idname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
