# Generated by Django 3.2.5 on 2021-07-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mweb', '0015_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='f1',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='f2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='f3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='f4',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='f5',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='f6',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='f7',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='f8',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
