# Generated by Django 3.2.5 on 2021-08-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mweb', '0016_auto_20210730_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Features',
        ),
    ]
